apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lurus-identity-route
  namespace: lurus-identity
  labels:
    app: lurus-identity
    app.kubernetes.io/part-of: lurus
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`identity.lurus.cn`)
      kind: Rule
      services:
        - name: identity-service
          port: 18104
  tls:
    secretName: lurus-cn-wildcard-tls
