apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: lurus-platform
  labels:
    app: lurus-notification
    app.kubernetes.io/name: lurus-notification
    app.kubernetes.io/part-of: lurus
spec:
  selector:
    app: lurus-notification
  ports:
    - name: http
      port: 18900
      targetPort: 18900
  type: ClusterIP
