apiVersion: v1
kind: ConfigMap
metadata:
  name: lurus-admin-config
  namespace: lurus-platform
data:
  NODE_ENV: "production"
  AUTH_TRUST_HOST: "true"
  NEXTAUTH_URL: "https://admin.lurus.cn"
  ZITADEL_ISSUER: "https://auth.lurus.cn"
  IDENTITY_SERVICE_URL: "http://platform-core.lurus-platform.svc.cluster.local:18104"
  NOTIFICATION_SERVICE_URL: "http://notification-service.lurus-platform.svc.cluster.local:18900"
