apiVersion: v1
kind: Secret
metadata:
  name: lurus-admin-secrets
  namespace: lurus-platform
type: Opaque
stringData:
  NEXTAUTH_SECRET: "CHANGE_ME_32_CHAR_RANDOM_STRING"
  ZITADEL_CLIENT_ID: "CHANGE_ME"
  ZITADEL_CLIENT_SECRET: "CHANGE_ME"
