apiVersion: v1
kind: ConfigMap
metadata:
  name: lurus-login-config
  namespace: lurus-platform
data:
  PORT: "3000"
  TZ: "Asia/Shanghai"
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"
  ZITADEL_API_URL: "https://auth.lurus.cn"
  # TLS terminated at Traefik, not needed here
  NEXT_PUBLIC_THEME_ROUNDNESS: "mid"
  NEXT_PUBLIC_THEME_LAYOUT: "top-to-bottom"
  NEXT_PUBLIC_THEME_APPEARANCE: "material"
  NEXT_PUBLIC_THEME_SPACING: "regular"
