apiVersion: v1
kind: Service
metadata:
  name: lurus-login
  namespace: lurus-login
  labels:
    app: lurus-login
spec:
  selector:
    app: lurus-login
  ports:
    - port: 3000
      targetPort: 3000
      name: http
